### ISSUE TITLE
 many indels when aligning PacBio data to reference

### ISSUE THREAD

**Issue by HannahJusten** [mchaisso/blasr#10]
Hello,

I am using blasr to align PacBio raw long reads (older generation) to a reference genome.

$ blasr raw.pacbio.subreads.bam reference.fasta --bam --out out.bam 

I indexed the bam file after using samtools:

$ samtools sort -@ 8 out.bam  -o out_sorted.bam 
$ samtools index out_sorted.bam 

When I view the alignment in IGV it appears like there is something wrong with the alignment as there are a lot of indels present:

![image](https://user-images.githubusercontent.com/26040767/190460704-41419dce-b2ea-4e34-adbc-fb333e50ff1d.png)

Does anybody have any suggestions on which flags to add to improve the alignment? Or what could have gone wrong in this alignment?

Any advice is very much appreciated!
Thank you in advance!
Hannah

**Comment by mchaisso** [comment]
The older reads likely just have lots of indels!  Also, support for blasr ended in 2012, and I recommend using lra or minimap to align your reads.
