### ISSUE TITLE
How can I run BLASR with contig files larger than 4 Gb?

### ISSUE THREAD

**Issue by cgy0627** [mchaisso/blasr#9]
Hi,

I ran BLASR with a contig file that is approximately 19 Gb, from which I got the following error:

`ERROR! Reading fasta files greater than 4Gbytes is not supported.`

Could I simply split up my contig file into multiple files containing < 4 Gb fasta sequences, run BLASR on each of them separately, and cat the output files afterwards for downstream analysis? Or would this output file be different from what I would've gotten from running it just once on the 19 Gb file (if that was possible)?

Thanks in advance.

Jenny

**Comment by mchaisso** [comment]
Hi Jenny - blasr is no longer supported.  I recommend you use lra or
minimap2, though I haven't tried lra on large genomes.

**Comment by cgy0627** [comment]
Ok, thanks!
